# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event_exim', '0001_initial'),
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address1', models.CharField(blank=True, max_length=765, null=True)),
                ('address2', models.CharField(blank=True, max_length=765, null=True)),
                ('city', models.CharField(blank=True, max_length=765, null=True)),
                ('state', models.CharField(blank=True, max_length=765, null=True)),
                ('region', models.CharField(blank=True, max_length=765, null=True)),
                ('postal', models.CharField(blank=True, max_length=765, null=True)),
                ('zip', models.CharField(blank=True, max_length=15, null=True)),
                ('plus4', models.CharField(blank=True, max_length=12, null=True)),
                ('country', models.CharField(blank=True, max_length=765, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('title', models.CharField(max_length=765)),
                ('starts_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('starts_at_utc', models.DateTimeField(blank=True, null=True)),
                ('ends_at_utc', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('cancelled', 'cancelled'), ('deleted', 'deleted')], db_index=True, max_length=96)),
                ('host_is_confirmed', models.IntegerField()),
                ('is_private', models.IntegerField(choices=[(0, 'public'), (1, 'private')], verbose_name='private or public')),
                ('is_approved', models.IntegerField()),
                ('attendee_count', models.IntegerField()),
                ('max_attendees', models.IntegerField(blank=True, null=True)),
                ('venue', models.CharField(max_length=765)),
                ('phone', models.CharField(max_length=765)),
                ('public_description', models.TextField()),
                ('directions', models.TextField()),
                ('note_to_attendees', models.TextField()),
                ('notes', models.TextField()),
                ('organization_official_event', models.NullBooleanField()),
                ('event_type', models.CharField(max_length=765)),
                ('organization_campaign', models.CharField(db_index=True, max_length=765)),
                ('is_searchable', models.IntegerField(choices=[(0, 'not searchable'), (1, 'searchable')])),
                ('private_phone', models.CharField(max_length=765)),
                ('url', models.URLField(blank=True)),
                ('slug', models.SlugField(blank=True, max_length=255, null=True)),
                ('osdi_origin_system', models.CharField(max_length=765)),
                ('ticket_type', models.IntegerField(choices=[(0, 'ticketed'), (1, 'open'), (2, 'ticketed')])),
                ('share_url', models.URLField(blank=True)),
                ('political_scope', models.CharField(blank=True, max_length=765, null=True)),
                ('venue_category', models.IntegerField(choices=[(0, 'unknown'), (1, 'private home'), (2, 'public space'), (3, 'target location (e.g. congressional district office)'), (4, 'virtual')])),
                ('needs_organizer_help', models.IntegerField(blank=True, default=0, null=True)),
                ('rsvp_url', models.URLField(blank=True)),
                ('event_facebook_url', models.URLField(blank=True)),
                ('organization_status_review', models.CharField(blank=True, choices=[('', 'New'), ('reviewed', 'Reviewed'), ('vetted', 'Vetted'), ('questionable', 'Questionable'), ('limbo', 'Limbo')], db_index=True, max_length=32)),
                ('organization_status_prep', models.CharField(blank=True, choices=[('', 'Unclaimed'), ('claimed', 'Claimed'), ('partially_prepped', 'Partially prepped'), ('fully_prepped', 'Fully prepped'), ('nocontact', 'Unable to contact')], db_index=True, max_length=32)),
                ('dupe_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_store.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_email', models.CharField(blank=True, max_length=765, null=True)),
                ('email', models.CharField(blank=True, max_length=765, null=True)),
                ('name', models.CharField(blank=True, max_length=765, null=True)),
                ('host_system_id', models.CharField(max_length=765)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=765)),
                ('facebook', models.CharField(max_length=128)),
                ('twitter', models.CharField(help_text='do not include @', max_length=128)),
                ('url', models.URLField(blank=True)),
                ('slug', models.CharField(max_length=128)),
                ('logo_thumb', models.URLField(blank=True)),
                ('logo_big', models.URLField(blank=True)),
                ('privacy_policy', models.URLField(blank=True)),
                ('terms_and_conditions', models.URLField(blank=True)),
                ('osdi_source_id', models.CharField(max_length=128)),
                ('api_key', models.CharField(editable=False, max_length=765)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_store.Organization'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_store.Host'),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_exim.EventSource'),
        ),
    ]
