# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 16:07


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashed_email', models.CharField(blank=True, max_length=765, null=True)),
                ('email', models.CharField(blank=True, max_length=765, null=True)),
                ('name', models.CharField(blank=True, max_length=765, null=True)),
                ('member_system_id', models.CharField(max_length=765)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_store.Activist'),
        ),
        migrations.DeleteModel(
            name='Host',
        ),
    ]
