# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:44
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0004_auto_20170531_1444'),
        ('event_store', '0002_auto_20170530_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activist',
            name='member_system_id',
        ),
        migrations.AddField(
            model_name='activist',
            name='member_system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event_exim.EventSource'),
        ),
        migrations.AddField(
            model_name='activist',
            name='member_system_pk',
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
        migrations.AddField(
            model_name='activist',
            name='phone',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='organization_source_pk',
            field=models.CharField(blank=True, db_index=True, max_length=765, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='source_json_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activist',
            name='hashed_email',
            field=models.CharField(blank=True, help_text='sha256 hash hexdigest of the email address', max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='directions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(blank=True, max_length=765, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='note_to_attendees',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.CharField(blank=True, max_length=765),
        ),
        migrations.AlterField(
            model_name='event',
            name='private_phone',
            field=models.CharField(blank=True, max_length=765),
        ),
        migrations.AlterField(
            model_name='event',
            name='public_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='venue',
            field=models.CharField(blank=True, max_length=765),
        ),
    ]
