# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 15:14


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0003_auto_20170531_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_status_prep',
            field=models.CharField(blank=True, choices=[('', 'Unclaimed'), ('claimed', 'Claimed'), ('partially_prepped', 'Partially prepped'), ('fully_prepped', 'Fully prepped'), ('nocontact', 'Unable to contact')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_status_review',
            field=models.CharField(blank=True, choices=[('', 'New'), ('reviewed', 'Reviewed'), ('vetted', 'Vetted'), ('questionable', 'Questionable'), ('limbo', 'Limbo')], db_index=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='rsvp_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
