# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0005_auto_20170602_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source_json_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
