# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 23:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0005_auto_20170602_1835'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='dupe_id',
            new_name='dupe',
        ),
    ]
