# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0006_auto_20170614_2126'),
        ('event_store', '0006_auto_20170612_2350'),
    ]

    operations = [
    ]
