# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-16 15:06


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0007_merge_20170614_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='notes',
            new_name='internal_notes',
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_host',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_store.Activist'),
        ),
        migrations.AlterField(
            model_name='event',
            name='organization_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event_exim.EventSource'),
        ),
    ]
