# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 17:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0008_auto_20170616_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='organization_status_review',
            field=models.CharField(blank=True, choices=[(None, 'New'), ('reviewed', 'Reviewed'), ('vetted', 'Vetted'), ('questionable', 'Questionable'), ('limbo', 'Limbo')], db_index=True, max_length=32, null=True),
        ),
    ]
