# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-21 14:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDupeGuesses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.IntegerField(choices=[(0, 'undecided'), (1, 'not a duplicate'), (2, 'yes, duplicates')])),
            ],
        ),
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. campaign or just describe the system', max_length=128)),
                ('osdi_name', models.CharField(max_length=765)),
                ('crm_type', models.CharField(choices=[('actionkit_db', 'actionkit_db'), ('actionkit_api', 'actionkit_api')], max_length=16)),
                ('url', models.CharField(max_length=765)),
                ('username', models.CharField(max_length=765)),
                ('password', models.CharField(max_length=765)),
                ('token_pw1', models.CharField(max_length=765)),
                ('token_pw2', models.CharField(max_length=765)),
                ('token_pw3', models.CharField(max_length=765)),
                ('update_style', models.IntegerField(choices=[(0, 'manual only'), (1, 'ping'), (2, 'ping with event reference'), (3, 'daily pull'), (4, 'hourly')])),
                ('allows_updates', models.IntegerField(choices=[(0, 'no'), (1, 'yes')], default=0, help_text='as sink')),
                ('last_update', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Org2OrgShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_sink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_sinks', to='event_exim.EventSource')),
                ('event_source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='share_sources', to='event_exim.EventSource')),
            ],
        ),
    ]
