# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:44


import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0003_auto_20170530_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventsource',
            name='password',
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='token_pw1',
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='token_pw2',
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='token_pw3',
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='url',
        ),
        migrations.RemoveField(
            model_name='eventsource',
            name='username',
        ),
        migrations.AddField(
            model_name='eventsource',
            name='crm_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org2orgshare',
            name='filters',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
