# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-31 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0004_auto_20170531_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='last_update',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
