# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-12 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0005_auto_20170602_1835'),
        ('event_exim', '0005_auto_20170531_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='crm_type',
            field=models.CharField(choices=[('actionkit_api', 'actionkit_api')], max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='eventdupeguesses',
            unique_together=set([('source_event', 'dupe_event')]),
        ),
    ]
