# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 21:26


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0005_auto_20170531_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsource',
            name='crm_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='crm_type',
            field=models.CharField(choices=[('actionkit_api', 'actionkit_api')], max_length=16),
        ),
        migrations.AlterField(
            model_name='eventsource',
            name='origin_organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source', to='event_store.Organization'),
        ),
        migrations.AlterField(
            model_name='org2orgshare',
            name='filters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
