# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-13 22:13


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0007_auto_20170612_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdupeguesses',
            name='decision',
            field=models.IntegerField(choices=[(0, 'undecided'), (1, 'not a duplicate'), (2, 'yes, duplicates')], null=True, verbose_name='Status'),
        ),
    ]
