# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-14 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0008_auto_20170613_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdupeguesses',
            name='decision',
            field=models.IntegerField(blank=True, choices=[(0, 'undecided'), (1, 'not a duplicate'), (2, 'yes, duplicates')], null=True, verbose_name='Status'),
        ),
    ]
