# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 23:05


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_exim', '0009_auto_20170614_2036'),
        ('event_exim', '0006_auto_20170614_2126'),
    ]

    operations = [
    ]
