# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-02 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('event_store', '0005_auto_20170602_1835'),
        ('reviewer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_index=True, to='auth.Group')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, db_index=True, to='event_store.Organization')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='key',
            field=models.CharField(default='review', help_text='the data key for what is being reviewed -- this allows multiple keys per-object', max_length=128),
        ),
        migrations.AddField(
            model_name='review',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_store.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='event_store.Organization'),
            preserve_default=False,
        ),
    ]
