# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-25 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0009_auto_20170625_2222'),
        ('auth', '0008_alter_user_username_max_length'),
        ('reviewer', '0003_reviewlog_subject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewgroup',
            unique_together=set([('organization', 'group')]),
        ),
    ]
