# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-07-18 17:39


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event_store', '0009_auto_20180718_1739'),
        ('auth', '0008_alter_user_username_max_length'),
        ('reviewer', '0003_reviewlog_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='reviewgroup',
            unique_together=set([('organization', 'group')]),
        ),
    ]
