# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-08-07 22:15


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviewer', '0005_visibility_20180725'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviewlog',
            options={'permissions': (('message_sending', 'message sending'), ('bulk_message_sending', 'bulk message sending'), ('bulk_note_adding', 'bulk note adding'))},
        ),
        migrations.AddField(
            model_name='reviewlog',
            name='log_type',
            field=models.CharField(choices=[('note', 'Note'), ('message', 'Message'), ('bulk_msg', 'Bulk Message')], default='note', max_length=8),
        ),
        migrations.AlterField(
            model_name='reviewgroup',
            name='visibility_level',
            field=models.IntegerField(default=0, help_text='Think of it like an access hierarchy. 0 is generally the lowest level. Anything higher is probably staff/etc. You can see Reviews/ReviewLogs with your own visibility and lower'),
        ),
    ]
